# Publish Virtual Signal Head appearances to MQTT (JMRI → broker).
# HART Digicon lamps → LCOS packed IH### (node*100 + UID 32+index).
# Generated by cats/scripts/build_hart_signal_heads.py — see cats/data/signal_wiring.csv.
#
# Topic: track/signalhead/<systemName>   e.g. track/signalhead/IH432
# Payload: appearance name GREEN / YELLOW / RED / DARK / …
# Brick East Main West stays MQTT Signal Mast 464 (not listed here).
#
# Load after tables (profile Start Up). Requires JMRI MQTT connection.

import jmri
import java

class HartMqttSignalHeadPublisher(java.beans.PropertyChangeListener):
    def __init__(self, topic_prefix, head_names):
        self.topic_prefix = topic_prefix
        self.head_names = list(head_names)
        self.mqtt = None

    def start(self):
        memo = jmri.InstanceManager.getDefault(jmri.jmrix.mqtt.MqttSystemConnectionMemo)
        self.mqtt = memo.getMqttAdapter()
        for name in self.head_names:
            head = signals.getSignalHead(name)
            if head is None:
                print("HartMqttSignalHeadPublisher: missing head", name)
                continue
            head.addPropertyChangeListener(self)
            self._publish(head)
            print("HartMqttSignalHeadPublisher: listening", name)
        return

    def propertyChange(self, event):
        if event.propertyName == "Appearance":
            self._publish(event.source)
        return

    def _publish(self, head):
        topic = self.topic_prefix + head.getSystemName()
        data = head.getAppearanceName()
        print("HartMqttSignalHeadPublisher:", topic, data)
        self.mqtt.publish(topic, data)
        return

publisher = HartMqttSignalHeadPublisher(
    "track/signalhead/",
    ['IH432', 'IH433', 'IH434', 'IH435', 'IH436', 'IH437', 'IH1332', 'IH1333', 'IH1334', 'IH1335', 'IH1336', 'IH1337', 'IH1338', 'IH1232', 'IH1233', 'IH1234', 'IH1235', 'IH1236', 'IH1237', 'IH1238', 'IH1239', 'IH1240', 'IH1241', 'IH132', 'IH133', 'IH134', 'IH135', 'IH136', 'IH137', 'IH138', 'IH139', 'IH140', 'IH141'],
)
publisher.start()
